### ISSUE TITLE
got this error every time

### ISSUE THREAD

**Issue by sagar3506** [ninoseki/miteru#110]
![image](https://user-images.githubusercontent.com/9415704/65834657-e436aa80-e2fa-11e9-9584-5224b5c6538d.png)

**Comment by ninoseki** [comment]
It doesn't support Windows.

**Comment by sagar3506** [comment]
ok how can i use old version what to use v0.12.7
gem install miteru 0.12.7 ?

**Comment by ninoseki** [comment]
https://guides.rubygems.org/command-reference/#gem-install
