### ISSUE TITLE
target URLs

### ISSUE THREAD

**Issue by herve-sail88** [ninoseki/miteru#140]
Hi,

Is it possible to change the target URL to a specific domain like '.xyz' and  or network range ?

Cheers.

**Comment by ninoseki** [comment]
Excuses me, I cannot understand what you mean.(what is the target URL?)
Could you explain it detail?

**Comment by herve-sail88** [comment]
Sorry for not being clear. Thanks for the quick response. I would like to investigate any potential phishing kits on a list of domains or  URLs.  If I run 'miteru execute --auto-download'  it crawls through URLs. Where are the URLs coming from?  If possible, I would like to crawl through a list of predefined Phishing URLs, and or maybe URLs in a specific domain like '.xyz' as an example.  Cheers.

**Comment by ninoseki** [comment]
> Where are the URLs coming from? 
It is written in the README.

>  I would like to crawl through a list of predefined Phishing URL.
There is no such feature at the moment.
