### ISSUE TITLE
Ayashige error in scans.

### ISSUE THREAD

**Issue by SteveD3** [ninoseki/miteru#162]
Not sure if related, but after the update, the Ayashige feed stopped working. 

Error:
Failed to load ayashige feed (Miteru::HTTPResponseError)

Feed source:
https://ayashige.herokuapp.com/feed

If unrelated or a non-issue, please feel free to close. Just wanted to bring it to your attention.

**Comment by ninoseki** [comment]
Ayashige is operated by me on the best effort basis. It uses Heroku's free dyno and sometimes it runs out the free quota in the end of a month.
