### ISSUE TITLE
URLScan feed not pulling in

### ISSUE THREAD

**Issue by SteveD3** [ninoseki/miteru#169]
Sorry to open yet another issue.

But the URLScan feed isn't triggering in the script. The collection issue started on December 2, but I didn't report it as I thought it was temporary problem. Given that the problem has remained, thought it best to bring it to your attention, as the URLScan gem seems to be what is making the call.  

I've checked the database, and the only feeds that seem to be working are PhishStats and Ayashige. The miteru command I use has been the same one I've used since the start.

----
## Miteru command used:

/home/steved3/miteru execute --threads=12 --size=10000 --ayashige --auto-download --directory-traveling --download-to=/media/steved3/LINUX/miteru_kit_dl

----
## Troubleshooting: 
Attempted to alter the number of responses via --size (example: --size=9000) which didn't work.

When I visit the URLScan query directly via browser, it loads 10,000 results fine.
Example: https://urlscan.io/api/v1/search/?q=task.method:automatic

----
### November 30
Loaded 11023 URLs to crawl. (crawling in 12 threads)

### December 01
Loaded 10833 URLs to crawl. (crawling in 12 threads)

### December 02
Loaded 1664 URLs to crawl. (crawling in 12 threads)

### December 03
Loaded 1791 URLs to crawl. (crawling in 12 threads)

Image was taken 4 hours after this scan.

![miteru](https://user-images.githubusercontent.com/11821110/144590737-b3258944-03a4-448b-8c29-8ca8e027e008.jpg)

----

## Operational Details:
OS: Debian 10

steved3@steved3-lab:~$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

steved3@steved3-lab:~$ gem -v
3.2.32

steved3@steved3-lab:~$ gem which miteru
/home/steved3/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/miteru-1.1.0/lib/miteru.rb

**Comment by ninoseki** [comment]
Please check this tweet.
https://twitter.com/urlscanio/status/1466012487019552771?s=21

**Comment by ninoseki** [comment]
Also please do not share logs via a screenshot. It's difficult to understand.

**Comment by SteveD3** [comment]
Understood. Sorry about the image.
