### ISSUE TITLE
Most high-quality and updated phishing feed 

### ISSUE THREAD

**Issue by lindsey98** [ninoseki/miteru#170]
Hi ninoseki,
  Thanks for sharing the amazing phishing kit detection tool. May I ask do you have any idea among the list of phishing feed resources, which one provides the majority as well as high-quality number of phishing URLs? Which resource do you think is the most reliable and updated? Thanks
![1741644219942_ pic](https://user-images.githubusercontent.com/51521323/152748689-7cda1721-dca1-49b0-aa07-d890056982a1.jpg)

**Comment by ninoseki** [comment]
urlscan.io's pro feed is the best IMHO.
