### ISSUE TITLE
Add new feed

### ISSUE THREAD

**Issue by lindsey98** [ninoseki/miteru#171]
Hi ninoseki,
   May I ask if I want to add new feed source, which are the files I need to revise? Thanks for helping!

**Comment by ninoseki** [comment]
Sure of course. I will take a look at it if you could provide the details of a new source.

**Comment by lindsey98** [comment]
Thanks! I want to add the OpenPhish original URL feed (https://openphish.com/feed.txt) instead of the one filtered by urlscan.io

**Comment by ninoseki** [comment]
Excuse me, it does not make sense to me because that feed can be ingested via urlscan.io. 
It's OSS and you can fork this tool for free.

**Comment by ninoseki** [comment]
- Implement a feed in https://github.com/ninoseki/miteru/tree/master/lib/miteru/feeds
  - e.g. https://github.com/ninoseki/miteru/blob/master/lib/miteru/feeds/phishing_database.rb
- Include it in feeds:
  - https://github.com/ninoseki/miteru/blob/master/lib/miteru/feeds.rb#L27-L33 

That's all.

**Comment by lindsey98** [comment]
Thanks. From my understanding urlscan.io does not report all the URLs it obtained from Openphish, it has its inner filtering mechanisms based on the interactions with the URLs. Thus, any false negatives made by urlscan.io will be excluded. That's why I want to look at the original URLs instead.

**Comment by ninoseki** [comment]
You mean https://urlscan.io/search/#task.source%3Aopenphish is filtered?

**Comment by lindsey98** [comment]
![Screenshot 2022-02-08 at 5 50 02 PM](https://user-images.githubusercontent.com/51521323/152961892-7577828b-78be-49bf-b3da-e74730e121e8.png)
Yeah I think they submit those Openphish, Phishtank etc. internally and then use their tool to do a scanning

**Comment by lindsey98** [comment]
Anyway I will try and see. Thanks
