### ISSUE TITLE
Invalid byte sequence in GB2312

### ISSUE THREAD

**Issue by antHeater** [ninoseki/miteru#93]
![miteru2](https://user-images.githubusercontent.com/29625269/59434044-0dced300-8deb-11e9-95b2-85eb7eef486a.png)
Hi, this is from today, seems I still got encoding related issues...

**Comment by ninoseki** [comment]
Please post logs in a plain text format.

**Comment by antHeater** [comment]
`Traceback (most recent call last):
        20: from /var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:209:in `block (3 levels) in in_threads'
        19: from /var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:359:in `block in work_in_threads'
        18: from /var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:515:in `with_instrumentation'
        17: from /var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:360:in `block (2 levels) in work_in_threads'
        16: from /var/lib/gems/2.5.0/gems/parallel-1.17.0/lib/parallel.rb:506:in `call_with_index'
        15: from /var/lib/gems/2.5.0/gems/miteru-0.12.5/lib/miteru/crawler.rb:34:in `block in execute'
        14: from /var/lib/gems/2.5.0/gems/miteru-0.12.5/lib/miteru/crawler.rb:53:in `notify'
        13: from /var/lib/gems/2.5.0/gems/miteru-0.12.5/lib/miteru/website.rb:17:in `kits'
        12: from /var/lib/gems/2.5.0/gems/miteru-0.12.5/lib/miteru/website.rb:71:in `links'
        11: from /var/lib/gems/2.5.0/gems/miteru-0.12.5/lib/miteru/website.rb:71:in `map'
        10: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/node_set.rb:58:in `each'
         9: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/node_set.rb:58:in `each'
         8: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/node_set.rb:58:in `block in each'
         7: from /var/lib/gems/2.5.0/gems/miteru-0.12.5/lib/miteru/website.rb:71:in `block in links'
         6: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/element.rb:92:in `get'
         5: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/attribute.rb:72:in `value'
         4: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/entity_decoder.rb:5:in `try_decode'
         3: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/entity_decoder.rb:14:in `decode'
         2: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/html/entities.rb:2142:in `decode'
         1: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/entities.rb:74:in `decode'
/var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/entities.rb:74:in `gsub': invalid byte sequence in GB2312 (ArgumentError)
`
